#!/bin/bash

. ./test/helper.sh

function log() {
	if [[ -t 1 ]]; then
		printf "\x1b[1m\x1b[32m>>>\x1b[0m \x1b[1m%s\x1b[0m\n" "$1"
	else
		printf ">>> %s\n" "$1"
	fi
}

error=0

for test in ${0%/*}/*_test.fish; do
	log "Running $test under fish (interactive) ..."
	fish $* -ic "source test/fishtape.fish; fishtape $test" || error=1
	echo
done

for test in ${0%/*}/*_test.fish; do
	log "Running $test under fish (non-interactive) ..."
	fish $* -c "source test/fishtape.fish; fishtape $test" || error=1
	echo
done

exit "$error"
